on:
  push:
    branches: 
      - master
       
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: data/covid19za_provincial_confirmed_rt.csv
